### ISSUE TITLE
[BUG?] Visions of Heresy's cooldown doesn't get reduced by Attack Speed.

### ISSUE THREAD

**Issue by Neyowo** [Moffein/RiskyTweaks#2]
As title suggested, I can't make it work. I did try to disable every single mod but the dependencies and the Heretic mod, and the cooldown still doesn't get reduced by attack speed. Is it a bug introduced by Gearbox ?

**Comment by Moffein** [comment]
Thanks for reporting this, the issue has been fixed in both RiskyTweaks and HereticMod.

**Comment by Neyowo** [comment]
I'm very sorry to bring up the subject again, but unfortunately, the fix still doesn't work on my part... As further testing, I tried it with and without the mark of heresy. Moreover, I tried again with other mods, as well as with only dependencies. I also tried with only the Heretic Mod on. On the other end though, the Scrap Launcher fix works perfectly fine... At this point, I'm wondering if the problem isn't on my side. Sorry again.

**Comment by Moffein** [comment]
When you get the chance, post your LogOutput.log file.
You can find this by going to r2modman -> settings -> locations -> browse profile folder -> BepInEx/LogOutput.log

**Comment by Neyowo** [comment]
[LogOutput.log](https://github.com/user-attachments/files/17271457/LogOutput.log)
Hoping this works.

**Comment by Moffein** [comment]
Thanks, seems like the issue was that RiskyTweaks and Heretic were having some incompatibility as of the latest update. After updating RiskyTweaks to 1.3.9 and Heretic to 1.2.8, it should work.
Let me know how that goes once they show up in r2modman.

**Comment by Neyowo** [comment]
The bug appears to be fixed ! Tried with as many different parameters as possible -including with all mods-, and it worked everytime ! Thank you !
